import type { LucideIcon } from 'lucide-react';

/**
 * Content and data shapes for the site.
 *
 * `Tutor`, `Programme`, and `PricingTier` are derived field-for-field from the
 * `tutors`, `programs`, and `pricing` const arrays in src/App.tsx. Nothing is
 * added or renamed, so they can be applied to those arrays without edits.
 */

/** One entry in the `tutors` array (src/App.tsx). */
export interface Tutor {
  /** Display name, e.g. 'Amaka Okoye'. */
  name: string;
  /** Title shown under the name, e.g. 'Lead Igbo Language & Cultural Tutor'. */
  role: string;
  /** Two letters rendered large on the card face, e.g. 'AO'. */
  initials: string;
  /** Tailwind gradient stops for the card, e.g. 'from-amber-200 to-orange-600'. */
  color: string;
  /** Pull quote shown on the card, rendered inside curly quotes. */
  quote: string;
}

/** One entry in the `programs` array (src/App.tsx). */
export interface Programme {
  /** Small label above the title, e.g. '01 / Heritage'. */
  eyebrow: string;
  title: string;
  description: string;
  /** Checklist items rendered under the description. */
  bullets: string[];
  /** A lucide-react component reference, not a string — e.g. `BookOpen`. */
  icon: LucideIcon;
  /** Tailwind gradient overlay, e.g. 'from-amber-400/20 via-transparent to-transparent'. */
  accent: string;
}

/** One entry in the `pricing` array (src/App.tsx). */
export interface PricingTier {
  name: string;
  /** Pre-formatted display string including the currency symbol, e.g. '$100'. */
  price: string;
  /** Secondary rate line, e.g. '$25 / hour'. */
  detail: string;
  description: string;
  features: string[];
  /** Marks the highlighted 'MOST POPULAR' tier. */
  featured: boolean;
}

/** Options offered by the `age` select in the booking modal. */
export type ChildAgeBand = '4–6 years' | '7–9 years' | '10–12 years' | '13–16 years';

/** Options offered by the `subject` select in the booking modal. */
export type SubjectInterest = 'Igbo' | 'Math' | 'Both';

/** Options offered by the `time` select in the booking modal. */
export type PreferredTime =
  'Weekday mornings' | 'Weekday afternoons' | 'Weekday evenings' | 'Saturday';

/**
 * A row in `public.leads`.
 *
 * Field names are snake_case to match Postgres convention and are derived from
 * the six `name` attributes on the booking modal form in src/App.tsx
 * (name, email, phone, age, subject, time).
 *
 * NOTE: `public.leads` does not exist yet — no migration or SQL is in this
 * repo. Treat this interface as the proposed schema; reconcile it with the real
 * column names once it is created.
 *
 * Only `parent_name` and `email` are required. Everything else is optional so a
 * partial or abandoned submission can still be stored.
 */
export interface LeadSubmission {
  /** Primary key, generated by the database on insert. */
  id?: string;
  /** Insert timestamp, defaulted by the database. */
  created_at?: string;
  /** From the `name` input — the parent's full name. Required. */
  parent_name: string;
  /** From the `email` input. Required. */
  email: string;
  /** From the `phone` input. */
  phone?: string;
  /** From the `age` select. */
  child_age?: ChildAgeBand;
  /** From the `subject` select. */
  subject_interest?: SubjectInterest;
  /** From the `time` select. */
  preferred_time?: PreferredTime;
}
