import type { LucideIcon } from 'lucide-react';

/**
 * Content and data shapes for the site.
 *
 * `Tutor`, `Programme`, and `PricingTier` are derived field-for-field from the
 * `tutors`, `programs`, and `pricing` const arrays in src/App.tsx. Nothing is
 * added or renamed, so they can be applied to those arrays without edits.
 */

/** One entry in the `tutors` array (src/App.tsx). */
export interface Tutor {
  /** Display name, e.g. 'Amaka Okoye'. */
  name: string;
  /** Title shown under the name, e.g. 'Lead Igbo Language & Cultural Tutor'. */
  role: string;
  /** Two letters rendered large on the card face, e.g. 'AO'. */
  initials: string;
  /** Tailwind gradient stops for the card, e.g. 'from-amber-200 to-orange-600'. */
  color: string;
  /** Pull quote shown on the card, rendered inside curly quotes. */
  quote: string;
}

/** One entry in the `programs` array (src/App.tsx). */
export interface Programme {
  /** Small label above the title, e.g. '01 / Heritage'. */
  eyebrow: string;
  title: string;
  description: string;
  /** Checklist items rendered under the description. */
  bullets: string[];
  /** A lucide-react component reference, not a string — e.g. `BookOpen`. */
  icon: LucideIcon;
  /** Tailwind gradient overlay, e.g. 'from-amber-400/20 via-transparent to-transparent'. */
  accent: string;
}

/** One entry in the `pricing` array (src/App.tsx). */
export interface PricingTier {
  name: string;
  /** Pre-formatted display string including the currency symbol, e.g. '$100'. */
  price: string;
  /** Secondary rate line, e.g. '$25 / hour'. */
  detail: string;
  description: string;
  features: string[];
  /** Marks the highlighted 'MOST POPULAR' tier. */
  featured: boolean;
  /** Recorded as `plan_interest` when this card opens the booking modal. */
  planInterest: PlanInterest;
}

/** Options offered by the `age` select in the booking modal. */
export type ChildAgeBand = '4–6 years' | '7–9 years' | '10–12 years' | '13–16 years';

/** Options offered by the `subject` select in the booking modal. */
export type SubjectInterest = 'Igbo' | 'Math' | 'Both';

/** Options offered by the `timezone` select in the booking modal. */
export type TimeZoneOption =
  | 'United Kingdom (GMT/BST)'
  | 'US Eastern'
  | 'US Central'
  | 'US Mountain'
  | 'US Pacific'
  | 'Canada Eastern'
  | 'Canada Pacific'
  | 'Other';

/** Options offered by the `slot` select in the booking modal. */
export type PreferredSlot =
  | 'UK weekday evening (4-8pm)'
  | 'Saturday morning (North America)'
  | 'Sunday morning (North America)'
  | 'Flexible';

/**
 * Which call to action opened the booking modal.
 *
 * The three pricing cards report the tier the parent clicked; the header, hero,
 * mobile drawer, and closing CTA all report a plain trial request.
 */
export type PlanInterest = 'trial' | 'starter' | 'dual' | 'cohort';

/**
 * A row in `public.leads`.
 *
 * Mirrors the live column list, in schema order. Only `parent_name` and `email`
 * are NOT NULL; everything else is optional so a partial submission can still be
 * stored. `id`, `created_at`, `source`, and `status` all have database defaults
 * and are normally omitted on insert.
 */
export interface LeadSubmission {
  /** uuid, generated by the database on insert. */
  id?: string;
  /** From the `name` input — the parent's full name. NOT NULL. */
  parent_name: string;
  /** From the `email` input. NOT NULL. */
  email: string;
  /** From the `phone` input. */
  phone?: string;
  /** Not captured by the booking form yet — reserved for a future country field. */
  country?: string;
  /** From the `timezone` select. */
  timezone?: TimeZoneOption;
  /** From the `age` select. */
  child_age?: ChildAgeBand;
  /** From the `subject` select. */
  subject_interest?: SubjectInterest;
  /** From the `slot` select. */
  preferred_slot?: PreferredSlot;
  /** Which call to action opened the modal. */
  plan_interest?: PlanInterest;
  /** Not captured by the booking form yet — reserved for a future free-text field. */
  message?: string;
  /** Database default: 'website'. */
  source?: string;
  /** Database default: 'new'. */
  status?: string;
  /** timestamptz, generated by the database on insert. */
  created_at?: string;
}
